"""Write docs/draaiboek-coverage.md: which podiumd-tests test covers each case of the PodiumD test draaiboek.

The draaiboek is TA's test-catalog/cases.yaml (the Excel "Testscript PodiumD 4.6", 546 cases, class
A automatable, B with a mock, C manual, N placeholder). A case is linked to TA specs by the catalog's
poc_dekking and by the draaiboek rows TA's specs cite ("Portaal r54"); MIGRATION.md then says where
each TA spec went. Run: python -m podiumd_tests.draaiboek <path to TA test-automation>.
"""

from __future__ import annotations

import re
import sys

from collections import Counter
from collections import defaultdict
from pathlib import Path

import yaml

from podiumd_tests.config import REPO_ROOT

# How TA's specs name a draaiboek tab when they cite a row.
CITED_SHEETS = {
    "AK": "Tests tbv Architectuurkaders",
    "ABC": "Functionele tests ABC",
    "Contact": "Functionele tests Contact",
    "Continuïteit": "Continuïteit - Connectiviteit",
    "FB": "Functionele tests FB",
    "Formulier": "Functionele tests Formulier",
    "ITA": "Functionele tests ITA",
    "Portaal": "Functionele tests Portaal",
    "ZAC": "Functionele tests ZAC",
}
CITATION = re.compile(r"\b(" + "|".join(CITED_SHEETS) + r")[- ]r(\d+)\b")
TEST_FILE = re.compile(r"\btest_\w+\.py\b")
ROW = re.compile(r"^\| `([^`]+)` \|[^|]*\|[^|]*\| (\w+) \| (.*) \|$")


def migration() -> dict[str, tuple[str, str]]:
    """TA spec file name -> (decision, notes) from MIGRATION.md's TA section."""
    found: dict[str, tuple[str, str]] = {}
    section = ""
    for line in (REPO_ROOT / "MIGRATION.md").read_text(encoding="utf-8").splitlines():
        if line.startswith("## "):
            section = line[3:].strip()
        elif section == "TA" and (match := ROW.match(line)):
            found[Path(match[1]).name] = (match[2], match[3])
    return found


def cited(tests: Path) -> dict[tuple[str, int], set[str]]:
    """(sheet, Excel row) -> the TA spec files that cite it."""
    found: dict[tuple[str, int], set[str]] = defaultdict(set)
    for spec in tests.rglob("*.spec.ts"):
        for prefix, row in CITATION.findall(spec.read_text(encoding="utf-8")):
            found[CITED_SHEETS[prefix], int(row)].add(spec.name)
    return found


def status(specs: set[str], decisions: dict[str, tuple[str, str]]) -> str:
    """covered, blocked or dropped, from the decisions of the case's TA specs; "" without any."""
    kinds = {decisions.get(s, ("unknown", ""))[0] for s in specs}
    if kinds & {"port", "merge", "replace"}:
        return "covered"
    if "todo" in kinds:
        return "blocked"
    return "dropped" if kinds else ""


def main(ta: Path) -> None:
    """Write the report."""
    catalog = yaml.safe_load((ta / "test-catalog" / "cases.yaml").read_text(encoding="utf-8"))
    decisions = migration()
    citations = cited(ta / "tests")
    rows: list[str] = []
    totals: dict[str, Counter[str]] = defaultdict(Counter)
    for case in catalog["cases"]:
        specs = {p.split(":")[0] for p in case["poc_dekking"]} | citations.get(
            (case["sheet"], case["excel_rij"]), set()
        )
        state = status(specs, decisions) or ("no TA test" if case["klasse"] in {"A", "B"} else "out of scope")
        totals[case["klasse"]][state] += 1
        notes = " ".join(decisions[s][1] for s in specs if s in decisions and decisions[s][0] != "drop")
        where = ", ".join(f"`{name}`" for name in sorted(set(TEST_FILE.findall(notes))))
        text = re.sub(r"\s+", " ", str(case["sub"] or case["proces"])).replace("|", "/").replace("<", "&lt;")[:110]
        rows.append(f"| {case['test_id']} | {case['klasse']} | {state} | {text} | {where} |")
    states = ("covered", "blocked", "dropped", "no TA test", "out of scope")
    summary = ["| Class | " + " | ".join(states) + " |", "|---|" + "---|" * len(states)]
    summary += [f"| {k} | " + " | ".join(str(totals[k][s]) for s in states) + " |" for k in sorted(totals)]
    out = REPO_ROOT / "docs" / "draaiboek-coverage.md"
    out.write_text(
        "# Draaiboek coverage\n\n"
        "Generated by `python -m podiumd_tests.draaiboek` from TA's test-catalog (draaiboek PodiumD 4.6, 546 cases) "
        "and "
        "`MIGRATION.md`. Class A: automatable, B: with a mock, C: manual, N: placeholder. A case counts as "
        "covered when a TA spec that covers it (catalog mapping or a row the spec cites) was ported or merged. "
        '"no TA test": no TA spec covered it; tests that podiumd-tests added itself (e.g. the DigiD login) '
        "are not mapped to draaiboek cases, so some of these are covered after all.\n\n"
        + "\n".join(summary)
        + "\n\n| Case | Class | Status | Draaiboek | podiumd-tests files (from MIGRATION.md) |\n|---|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n",
        encoding="utf-8",
    )
    print(out)


if __name__ == "__main__":
    main(Path(sys.argv[1]))
